project:
  datasource:
    base:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.1.171:9999/mims
      username: jiapp
      password: jiapp
      mybatis-configPath: classpath:/mybatis/mybatis-config.xml
      mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
    map:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.1.171:9999/mims
      username: jiapp
      password: jiapp
      mybatis-configPath: classpath:/mybatis/mybatis-config.xml
      mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
  data-path: /data/jiapp/data_dir
  mapserver:
    binary: /usr/local/bin/mapserv
  los:
    host: http://211.172.246.71
    height-port: 11160
    minio-port: 11170
    accessKey: minioadmin
    secretKey: minioadmin

logging:
  pattern:
    console: "%blue(%-5level) %yellow(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr([%t]){green} %cyan(%logger[%method:%line]) - %magenta(%msg%n)"
    file: "%blue(%-5level) %yellow(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr([%t]){green} %cyan(%logger[%method:%line]) - %magenta(%msg%n)"
  level:
    com.jiin.admin: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.thymeleaf: INFO
    org.mybatis: INFO
    com.zaxxer: INFO
  file:
    name: /data/jiapp/data_dir/logs/admin_log.log
    max-size: 50MB