project:
  map-datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    mybatis-configPath: classpath:/mybatis/mybatis-config.xml
    mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
  path:
    cache: classpath:/static/data/cache/
    data: classpath:/static/data/data/
    mapnik: classpath:/static/data/mapnik/
    mapserver: classpath:/static/data/mapserver/
    proxy: classpath:/static/data/proxy/
    tmp: classpath:/static/data/tmp/
    vectortiles: classpath:/static/data/vectortiles/