project:
  datasource:
    base:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.1.174:9999/mims
      username: jiapp
      password: jiapp
      mybatis-configPath: classpath:/mybatis/mybatis-config.xml
      mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
    map:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.1.174:9999/mims
      username: jiapp
      password: jiapp
      mybatis-configPath: classpath:/mybatis/mybatis-config.xml
      mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
  data-path: /data/jiapp/data_dir
  mapserver:
    binary: /usr/local/bin/mapserv
  docker-name:    # docker service name
    mapproxy-name: jiin-mapproxy
    mapserver-name: jiin-server-1
    mapnik-name: jiin-server-2
    height-name: jiin-height
    rabbitmq-name: jiin-rabbitmq
  server-port:    # service port
    mapproxy-port: 11120
    mapserver-port: 11130
    mapnik-port: 11140
    terrain-port: 11150
    height-port: 11160
    vector-port: 11170

logging:
  pattern:
    console: "%blue(%-5level) %yellow(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr([%t]){green} %cyan(%logger[%method:%line]) - %magenta(%msg%n)"
    file: "%blue(%-5level) %yellow(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr([%t]){green} %cyan(%logger[%method:%line]) - %magenta(%msg%n)"
  level:
    root: ERROR
    com.jiin.admin: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.thymeleaf: INFO
    org.mybatis: INFO
    com.zaxxer: INFO
  file:
    name: /data/jiapp/data_dir/logs/admin_log.log
    max-size: 50MB