project:
  datasource:
    base:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      mybatis-configPath: classpath:/mybatis/mybatis-config.xml
      mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
    map:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      mybatis-configPath: classpath:/mybatis/mybatis-config.xml
      mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
  data-path: /Users/PIG/SourceTree/admin-view/data/data_dir
  mapserver:
    binary: /usr/local/bin/mapserv
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop