### 스프링 encoding
spring:
  profiles:
    ## 개발 : local / 운영 : prod / 외부 : outside(박찬신)
    active: local
  http:
    encoding:
      charset: UTF-8
  datasource:
    driver-class-name: ${project.datasource.base.driver-class-name}
    url: ${project.datasource.base.url}
    username: ${project.datasource.base.username}
    password: ${project.datasource.base.password}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: false
      hibernate.enable_lazy_load_no_trans: true
      hibernate.jdbc.batch_size: 100
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
    open-in-view: true
  servlet:
    multipart:
      enabled: false
      max-file-size: -1
      max-request-size: -1
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  jackson:
    serialization:
      fail-on-empty-beans: false
  devtools:
    livereload:
      enabled: true

### tomcat 서버
server:
  port: 8077
  error:
    ## 개발모드 default : naver
    include-stacktrace: always
    whitelabel:
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /admin-view
