project:
  datasource:
    base:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      mybatis-configPath: classpath:/mybatis/mybatis-config.xml
      mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
    map:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      mybatis-configPath: classpath:/mybatis/mybatis-config.xml
      mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
  data-path: /data/jiserver/data_dir
  mapserver:
    binary: /usr/local/bin/mapserv
  los:
    host: http://192.168.99.100
    port: 9000
    accessKey: minioadmin
    secretKey: minioadmin
logging:
  level:
    org.springframework : INFO
    org.springframework.web : INFO