project:
  datasource:
    base:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://211.172.246.71:5000/mims
      username: jiserver
      password: jiserver
      mybatis-configPath: classpath:/mybatis/mybatis-config.xml
      mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
    map:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://211.172.246.71:5000/mims
      username: jiserver
      password: jiserver
      mybatis-configPath: classpath:/mybatis/mybatis-config.xml
      mybatis-mapperLocations: classpath:mybatis/map/**/*.xml
  data-path: /data/jiapp/data_dir
  mapserver:
    binary: /usr/local/bin/mapserv
  los:
    host: http://211.172.246.71
    heightPort: 11160
    minioPort: 11170
    accessKey: minioadmin
    secretKey: minioadmin
  log:
    config:
      path: /data/jiapp/data_dir/logs
      filename: admin_log
    level:
      root: DEBUG
      spring: DEBUG
      admin: DEBUG
      hibernate: DEBUG
      thymeleaf: DEBUG