### 스프링 encoding
spring:
  profiles:
    ## 개발 : local / 운영 : prod / 외부 : outside(박찬신)
    active: "local"
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  jackson:
    serialization:
      fail-on-empty-beans: false
  devtools:
    livereload:
      enabled: true

### tomcat 서버
server:
  port: 8077
  error:
    ## 개발모드 default : naver
    include-stacktrace: always
    whitelabel:
      enabled: true
  tomcat:
    uri-encoding: UTF-8
